### ISSUE TITLE
Supprted nodejs version?

### ISSUE THREAD

**Issue by lukavia** [i404788/GT5F-USB-js#1]
Hi, 
I've tried to install this module with nodejs versions v12.22.9 and v18.15.0 but I always get 
```89 error ../usb_module.cc: In function ‘void receiverawdata(const Nan::FunctionCallbackInfo<v8::Value>&)’:
89 error ../usb_module.cc:47:59: error: no matching function for call to ‘v8::Value::NumberValue()’
89 error    47 |     unsigned int size = (unsigned int)args[0]->NumberValue();
89 error       |                                       ~~~~~~~~~~~~~~~~~~~~^~
```

Which nodejs version should we use? 
Or can you update the module to support those nodejs versions, please?

**Comment by i404788** [comment]
Hey, 

I haven't used the nodejs side of this package in a while (even though I recently refactored the C side of it https://github.com/i404788/GT5F-USB-js/tree/v2). But I see the error you're getting, originally this was written for node 8.x or 10.x iirc, but I will update it to support 16.x at least (since that's what I have installed at the moment).

**Comment by i404788** [comment]
I've updated the library to work with Node 16.x and all recent version I think, but I haven't tested it yet as I don't have a scanner nearby.

Also I've added a python 'library' using cppyy which I hadn't published yet (this one has been tested), it has many more pre-made functions so you can use it as reference or if you aren't language dependent you might find that more convenient to use.

Let me know  if you run into any issues

**Comment by lukavia** [comment]
That is great. Thank you very much. 
I've tried the python code since it would be easier for me to use it, but I get another error with it:

```
Traceback (most recent call last):
  File "/home/lukav/Apps/GT5F-USB-js/gt5.py", line 7, in <module>
    cppyy.cppdef(f'#include "{usb_lib_path}"' +
  File "/home/lukav/.local/lib/python3.10/site-packages/cppyy/__init__.py", line 205, in cppdef
    raise SyntaxError('Failed to parse the given C++ code%s' % err.err)
SyntaxError: Failed to parse the given C++ code
In file included from input_line_18:1:
/home/lukav/Apps/GT5F-USB-js/usb_protoc.hpp:135:18: error: variable-sized object may not be initialized
  uint8_t packet[len + 6] = {0, 0, 1, 0};
                 ^~~~~~~
/home/lukav/Apps/GT5F-USB-js/usb_protoc.hpp:153:18: error: variable-sized object may not be initialized
  uint8_t packet[buf_size + 6] = {0};
                 ^~~~~~~~~~~~

```

**Comment by i404788** [comment]
Hmm strange that I didn't catch that while compiling the node version, but it should be fixed now.

**Comment by lukavia** [comment]
Perfect! Thank you very much. I'll let you know if I find something else.
